### ISSUE TITLE
fastqutils bfq can't decode it's own output

### ISSUE THREAD

**Issue by amcdavid** [ngsutils/ngsutils#11]
$ cat testfastq.fastq 
@aa/1
AAACTCTACAGACAATACATCCGTAATTTTTTCCAGCTTATCTAGTTGCTTTCTGATCCTTAGCTTCTCGAAACCGACGATAGCGCTTCGAATTAAGTCT
+
dbdddcdd_da_cccWcbcccccBcccbbcd^dddededeeee_e^dddbdacWaaddadbd^bdYbccdaaaVWbabaZQbaS^\Z^ZQYYQ`\cZccd
@bb/1
CTCAGTAGATCGTGGGCCGTAGCTTCGCGCATCTCTGAGGGCACC
+
BPMKSSQPPNY[][YY[][[YYSYY______Z_[_U^^^^_____

$ fastqutils bfq testfastq.fastq -o tfq.bfq
$ fastqutils bfq -d tfq.bfq > tfq.roundtrip
Traceback (most recent call last):
  File "/home/amcdavid/src/ngsutils-ngsutils-0.5.7/bin/..//ngsutils/fastq/bfq.py", line 710, in <module>
    bfq_decode(fnames[0])
  File "/home/amcdavid/src/ngsutils-ngsutils-0.5.7/bin/..//ngsutils/fastq/bfq.py", line 396, in bfq_decode
    bfq = BFQ(fname)
  File "/home/amcdavid/src/ngsutils-ngsutils-0.5.7/bin/..//ngsutils/fastq/bfq.py", line 160, in __init__
    self._read_header()
  File "/home/amcdavid/src/ngsutils-ngsutils-0.5.7/bin/..//ngsutils/fastq/bfq.py", line 258, in _read_header
    self.description, = struct.unpack('<%ss' % lendesc, self.fobj.read(lendesc))
struct.error: unpack requires a string argument of length 3444317596

So it looks like it's unpacking `lendesc` improperly, but without documentation or knowledge of what the binary format is, I don't think I have any hope of fixing it myself.

**Comment by mbreese** [comment]
I'm impressed that this was found - it was a hidden module. I removed the command from git HEAD. If you're interested in a more compact tool for FASTQ files, please check out this one: https://github.com/compgen-io/sqz.  It's an updated version of the same concept, and it is supported.
