### ISSUE TITLE
error: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by mchimenti** [ngsutils/ngsutils#25]
Hello,

Trying to install ngsutils on a Linux cluster.  Downloaded the repo, unzipped and un-tarred it and went into the directory.  Typed "make."  

"Make" fails with the following cryptic error: 

error: command 'gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /Users/mchiment/ngsutils-ngsutils-0.5.8/venv/bin/python -c "import setuptools, tokenize;__file__='/Users/mchiment/ngsutils-ngsutils-0.5.8/venv/build/pysam/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-eYZ75r-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/mchiment/ngsutils-ngsutils-0.5.8/venv/include/site/python2.7 failed with error code 1 in /Users/mchiment/ngsutils-ngsutils-0.5.8/venv/build/pysam
Traceback (most recent call last):
  File "/Users/mchiment/ngsutils-ngsutils-0.5.8/venv/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/Users/mchiment/ngsutils-ngsutils-0.5.8/venv/lib/python2.7/site-packages/pip/__init__.py", line 185, in main
    return command.main(cmd_args)
  File "/Users/mchiment/ngsutils-ngsutils-0.5.8/venv/lib/python2.7/site-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 40: ordinal not in range(128)
make: *** [init] Error 1

-----

Any suggestions are appreciated.  Thanks,

Michael

**Comment by mbreese** [comment]
What version of Linux is this for? Given the Unicode error, I'm assuming that somewhere there is a non-ascii character. However, that error isn't coming from my code, so perhaps it's in a directory name someplace? 

Do you have any other error messages?

**Comment by mchimenti** [comment]
Hi, thanks for the reply.  Linux is CentOS 6.4.  I didn't see any other errors.  Where should I look for non-ascii characters?  The tool installation directories?

**Comment by mbreese** [comment]
Just to be safe, try downloading the newest version. I just pushed a new release over the weekend for some other bug fixes.

I test mainly on CentOS, so this shouldn't be the problem. Occasionally I'll see errors on Ubuntu, but rarely does it happen on CentOS.

You should also look in /Users/mchiment/.pip/pip.log to see if there are any errors in there.

**Comment by ahalpern** [comment]
I ran into the same problem.  In my case, the cause seems to have been gcc running out of memory (due to process limits rather than actual RAM limits); running on another similarly configured host where the memory limits were higher, everything worked fine.  See the following link for an explanation: http://stackoverflow.com/questions/20555761/pip-install-pandas-gives-unicodedecodeerror-ascii-codec-cant-decode-byte-0
